variable "security_group_id" { type = string }
variable "env" { default = "dev" }
variable "project_name" { default = "visitor-log-system" }
variable "public_subnet" { type = list(string) }
variable "packer_based_ami_id" { type = string }
variable "target_group_arns" { type = list(string) }
variable "instance_type" { type = string }
variable "region" { type = string}
variable "iam_instance_profile_name" { type = string }