name: Deploy Dev (ap-south-1)

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [deploy-to-dev]
  workflow_dispatch:

jobs:
  call-deploy:
    uses: ./.github/workflows/terraform-deploy-dev.yaml
    permissions:
      id-token: write
      contents: read
    with:
      environment: dev
      region: ap-south-1
    secrets:
      oidc_role_name: ${{ secrets.OIDC_ROLE_NAME }}
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
